
services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
      - TABLE_NAME=${TABLE_NAME}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./service_account.json:/app/service_account.json:ro
      - ./run_spark_job.sh:/app/run_spark_job.sh:ro
      - ./spark_job.py:/app/spark_job.py:ro
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - kafka_network

  spark-worker-1:
    image: bitnami/spark:3.5.4
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - kafka_network

  spark-worker-2:
    image: bitnami/spark:3.5.4
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka_network
    external: true
